name: Pull request Review

on:
  pull_request_review:
    
jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
        
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: ['testing'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
  changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(github)
  
