name: Pull request

on:
  pull_request_target:
    types: [opened]
    
jobs:
  opened:
    name: On PR opened
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v6
        name: Add review label
        if: ${{ github.event.pull_request.draft == false }}
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
        
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: ['review'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Add wip label
        uses: actions/github-script@v6
        if: ${{ github.event.pull_request.draft == true }}
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
        
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: ['wip'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
