name: Pull request

on:
  pull_request_target:
    types: [opened]
  pull_request_review:
    
jobs:
  opened:
    name: On opened
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Add review label
        if: ${{ github.event.pull_request.draft == false }}
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
        
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: ['review'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Add wip label
        if: ${{ github.event.pull_request.draft == true }}
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
        
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: ['wip'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Add release label
        if: ${{ startsWith(github.event.pull_request.title, 'release:') }}
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
        
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: ['release'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
  reviews:
    name: On reviews
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Add testing label
      uses: pullreminders/label-when-approved-action@1.0.7
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "testing"
        REMOVE_LABEL: "review"
