name: Pull request

on:
  pull_request_target:
    types: [opened]
    
jobs:
  opened:
    name: On PR opened
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v6
        if: ${{ github.event.pull_request == 'draft' }}
        name: Add review label
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
            const isDraft = context.payload.pull_request.draft
          
            console.log(context)
            github.rest.issues.addLabels({
              issue_number: pullRequestId,
              labels: [isDraft ? 'wip' : 'review'],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
