name: Github release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Create new github release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pre-release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, '-') == true
        with:
          prerelease: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, '-') == false
