name: Github release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Create new github release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get
        id: get
        run: |
          MESSAGE=$(npx extract-changelog-release << EOF
          EOF
          )
          echo TEST=$MESSAGE >> $GITHUB_OUTPUT
      - name: Test
        run: echo ${{ steps.get.outputs.TEST }}
      - name: Pre-release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, '-') == true
        with:
          body: ${{ steps.get.outputs.TEST }}
          prerelease: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: contains(github.ref, '-') == false
        with:
          body: ${{ steps.get.outputs.TEST }}
