name: WUI Demo link

on:
  pull_request:
    types: [opened]

jobs:
  add_links_to_demo:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pullRequestId = context.payload.pull_request.number
            const pullRequestBranch = context.payload.pull_request.head.ref
            const pullRequestBody = context.payload.pull_request.body
            
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestId,
              body: `${body}
              🌞 DEMO: https://${pullRequestBranch}--welcome-ui.netlify.app 🌞` 
            });
