name: WUI Demo link

on:
  pull_request:
    types: [opened]

jobs:
  add_links_to_demo:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pullRequestId = context.payload.number
            console.log(github.rest.pulls)
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestId,
              body: `https://${pullRequestId}--welcome-ui.netlify.app`
            });
