on:
  pull_request:
    types: [opened]
jobs:
  add_links_to_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print the url to the demo
        run: echo The url is https://${GITHUB_REF_NAME}--welcome-ui.netlify.app
