on:
  pull_request:
    types: [opened]
jobs:
  add_links_to_demo:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit $GITHUB_REF --body "coco"
